--luacheck: globals set_keywords set_gui
set_keywords("comments", "828282")
set_keywords("reserved", "49483E")
set_keywords("string", "ffffff")
set_keywords("binary", "ffffff")
set_keywords("symbol", "ffffff")
set_keywords("variable", "ffffff")
set_keywords("operator", "ffffff")
set_keywords("error", "ff0000")
set_keywords("function", "ffff00")
set_keywords("member", "ffffff")

set_gui("background_color", "ff0000")
set_gui("font_color", "ffff00")
set_gui("current_line_color", "000000")
set_gui("selection_color", "ffff00")
set_gui("word_highlighted_color", "49483E")
set_gui("completion_background_color", "49483E")
set_gui("completion_selected_color", "75715E")
set_gui("caret_color", "f8f8f0")
