set_keywords("reserved", "624c83")
set_keywords("string", "6f894e")
set_keywords("binary", "ffa066")
set_keywords("symbol", "4e8ca2")
set_keywords("variable", "545464") --- XXX: same as foreground
set_keywords("operator", "836f4a")
set_keywords("comments", "8a8980")
set_keywords("error", "e82424")
set_keywords("function", "4d699b")
set_keywords("member", "77713f")

set_gui("background_color", "f2ecbc")
set_gui("current_line_color", "dcd5ac")
set_gui("selection_color", "c9cbd1")
set_gui("word_highlighted_color", "c9cbd1")
set_gui("font_color", "545464")
set_gui("completion_background_color", "c7d7e0")
set_gui("completion_selected_color", "9fb5c9")
set_gui("caret_color", "545464")
