highlight(">", "reserved")
highlight("<", "reserved")
highlight("+", "reserved")
highlight("-", "reserved")
highlight(".", "function")
highlight(",", "function")
highlight("[", "symbol")
highlight("]", "symbol")

add_comment("I love brainfuck 🥵")
add_comment("LETS MAKE OUR BRAIN HURT 🤯🤯🤯")
add_comment("Brainfuck is the best programming language 🧠🔥")
add_comment("++++++++++[>+++++++>++++++++++>+++>+<<<<-]\n>++.>+.+++++++..+++.>++.<<+++++++++++++++.\n>.+++.------.--------.>+.>.")
